site_name: Отчёты по лабораторным
theme:
  name: material

nav:
  - ЛР 1:
      - Главная: lab1/index.md
      - Задание 1: lab1/task1.md
      - Задание 2: lab1/task2.md
      - Задание 3: lab1/task3.md
      - Задание 4: lab1/task4.md
      - Задание 5: lab1/task5.md
  - ЛР 2:
      - Главная: lab2/index.md
      - Запуск и использование: lab2/startup.md
      - API и интерфейс: lab2/api.md
      - Администрирование: lab2/admin.md